name: Test functions
on: [push]
jobs:
  test_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -e .
      - name: Test functions on GitHub
        run: |
          python -m pytest